name: treadmill-ci-dev-branch

env:
  TERM: xterm # Makes tput work in actions output

# Controls when the action will run. Triggers the workflow on commits to the dev branch
on:
  push:
    branches:
      - dev/multiple_board_thci_clean
  # Manually dispatch for a specific branch
  workflow_dispatch:
    inputs:
      tock-kernel-ref:
        description: 'Ref (revision/branch/tag) of the upstream Tock repo to test'
        required: true
        default: 'master'
      libtock-c-ref:
        description: 'Ref (revision/branch/tag) of the upstream libtock-c repo to test'
        required: true
        default: 'master'
      tests-json:
        description: 'tests-json value passed to HWCI workflow (if empty, output from analyze-changes step is used)'
        required: false

permissions:
  contents: read

jobs:
  analyze-changes:
    runs-on: ubuntu-latest

    outputs:
      hwci-tests-json: ${{ steps.analyze-changes.outputs.hwci-tests-json }}

    steps:
      # This is not run within the context of a repository that contains actual
      # kernel / userspace code, so there is nothing for us to analyze. Instead
      # we clone this very repository and select all test definitions:
      - name: Checkout the tock-hardware-ci repository
        uses: actions/checkout@v4
        with:
          path: tock-hardware-ci

      - name: Checkout the tock/tock repository
        uses: actions/checkout@v4
        with:
          # Checkout the repository at the commit that triggered the workflow
          repository: tock/tock
          path: tock-tock

      - name: Select all defined tests
        id: analyze-changes
        run: |
          # Run the select_tests.py script
          python3 tock-hardware-ci/hwci/select_tests.py \
            --repo-path tock-tock \
            --hwci-path tock-hardware-ci/hwci \
            --output selected_tests.json

          echo "Selected HWCI tests:"
          cat selected_tests.json

          # Output the tests JSON
          hwci_tests_json=$(cat selected_tests.json | jq -c '.')
          echo "hwci-tests-json=${hwci_tests_json}" >> "$GITHUB_OUTPUT"

  run-treadmill-ci:
    needs: [analyze-changes]

    uses: ./.github/workflows/treadmill-ci.yml

    # This checks whether there is at least one test to run, see
    # https://github.com/orgs/community/discussions/27125#discussioncomment-3254720
    if: fromJSON(needs.analyze-changes.outputs.hwci-tests-json)[0] != null

    with:
      # Only run on a specific repository, as others will not have the right
      # environments set up and secrets configured. Forks may want to change
      # this parameter.
      repository-filter: 'tock/tock-hardware-ci'

      # Provide access to the required Treadmill secrets by running in the
      # appropriate environment
      job-environment: 'treadmill-ci-merged'

      # This workflow tests the tock-hardware-ci scripts itself, so take the
      # current GITHUB_SHA:
      tock-hardware-ci-ref: ${{ github.sha }}

      # Use the latest upstream Tock kernel / userspace components:
      tock-kernel-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tock-kernel-ref || 'master' }}
      libtock-c-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.libtock-c-ref || 'master' }}
      tests-json: ${{ (github.event_name == 'workflow_dispatch' && inputs.tests-json != '') && inputs.tests-json || needs.analyze-changes.outputs.hwci-tests-json }}

    secrets: inherit