name: treadmill-ci-dev-branch

env:
  TERM: xterm # Makes tput work in actions output

# Controls when the action will run. Triggers the workflow on commits to the dev branch
on:
  # Regular CI on the long-lived dev branch
  push:
    branches:
      - dev/multiple_board_thci_clean

  # CI requested by the GitHub Merge Queue
  # • fires once per merge-group creation
  # • filtered to groups that will merge into main or any dev/* branch
  merge_group:
    branches: [main, dev/**]
    types: [checks_requested]

  # Manually dispatch for a specific branch
  workflow_dispatch:
    inputs:
      tock-kernel-ref:
        description: 'Ref (revision/branch/tag) of the upstream Tock repo to test'
        required: true
        default: 'master'
      libtock-c-ref:
        description: 'Ref (revision/branch/tag) of the upstream libtock-c repo to test'
        required: true
        default: 'master'
      tests-json:
        description: 'tests-json value passed to HWCI workflow (if empty, output from analyze-changes step is used)'
        required: false

permissions:
  contents: read

jobs:
  analyze-changes:
    runs-on: ubuntu-latest

    outputs:
      hwci-tests-json: ${{ steps.analyze-changes.outputs.hwci-tests-json }}

    steps:
      # This is not run within the context of a repository that contains actual
      # kernel / userspace code, so there is nothing for us to analyze. Instead
      # we clone this very repository and select all test definitions:
      - name: Checkout the tock-hardware-ci repository
        uses: actions/checkout@v4
        with:
          path: tock-hardware-ci

      - name: Checkout the tock/tock repository
        uses: actions/checkout@v4
        with:
          # Checkout the repository at the commit that triggered the workflow
          repository: tock/tock
          path: tock-tock

      - name: Select all defined tests
        id: analyze-changes
        run: |
          # Run the select_tests.py script
          python3 tock-hardware-ci/hwci/select_tests.py \
            --repo-path tock-tock \
            --hwci-path tock-hardware-ci/hwci \
            --output selected_tests.json

          echo "Selected HWCI tests:"
          cat selected_tests.json

          # Output the tests JSON
          hwci_tests_json=$(cat selected_tests.json | jq -c '.')
          echo "hwci-tests-json=${hwci_tests_json}" >> "$GITHUB_OUTPUT"

  run-treadmill-ci:
    needs: [analyze-changes]

    uses: ./.github/workflows/treadmill-ci.yml

    # Skip if the selector script found no tests
    if: fromJSON(needs.analyze-changes.outputs.hwci-tests-json)[0] != null

    with:
      repository-filter: 'tock/tock-hardware-ci'

      # Pick the right secrets automatically:
      # • merge-queue runs → environment `merge-queue-ci`
      # • everything else  → environment `treadmill-ci-merged`
      job-environment: ${{ github.event_name == 'merge_group'
                           && 'merge-queue-ci'
                           || 'treadmill-ci-merged' }}

      # Pass revision information straight through
      tock-hardware-ci-ref: ${{ github.sha }}
      tock-kernel-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tock-kernel-ref || 'master' }}
      libtock-c-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.libtock-c-ref || 'master' }}
      tests-json: ${{ (github.event_name == 'workflow_dispatch' && inputs.tests-json != '')
                       && inputs.tests-json
                       || needs.analyze-changes.outputs.hwci-tests-json }}

    secrets: inherit
